HTTP:
  Addr: ":8080"

GracePeriod: 10s

Clusters:
  - Input:
      Kafka:
        Name: local-gostash
        Brokers:
          - "localhost:9094"
          - "localhost:9095"
          - "localhost:9096"
        Topics:
          - logs
        Group: gostash
        Conns: 1
        Consumers: 2
        Processors: 4
        MinBytes: 1048576
        MaxBytes: 5242880
        Offset: last
    Filters:
      - Action: transfer
        Field: message
        Target: data
    Output:
      ElasticSearch:
        Hosts:
          - "http://localhost:9200"
          - "http://localhost:9201"
          - "http://localhost:9202"
        Index: "logs-{{yyyy.MM.dd}}"
        MaxChunkBytes: 5242880
        Compress: false
        TimeZone: UTC
